### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by dblock** [nesquena/rabl#632]
Right now on HEAD for me:

```
~/source/rabl/dblock (master)$ bundle
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Using rake 10.4.2
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.7.0
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.2.1
Using builder 3.2.2
Using activemodel 4.2.1
Using arel 6.0.0
Using activerecord 4.2.1
Using bson 1.7.1
Using hashie 3.4.2
Using msgpack 0.4.7
Using oj 2.12.9
Using plist 3.1.0
Using rabl 0.11.6 from source at .
Using rack 1.6.1
Using rack-protection 1.5.3
Using rack-test 0.6.3
Using rr 1.0.5
Using riot 0.12.7
Using tilt 2.0.1
Using sinatra 1.4.6
Using sqlite3 1.3.10
Using bundler 1.7.9
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
~/source/rabl/dblock (master)$ rake
/Users/dblock/.rvm/rubies/ruby-2.0.0-p598/bin/ruby -w -I"lib:lib:test" -rubygems -I"/Users/dblock/.rvm/gems/ruby-2.0.0-p598/gems/rake-10.4.2/lib" "/Users/dblock/.rvm/gems/ruby-2.0.0-p598/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/*_test.rb" 
/Users/dblock/.rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.9/lib/bundler/source/rubygems.rb:191: warning: shadowing outer local variable - spec
/Users/dblock/source/rabl/dblock/test/partials_test.rb:97: warning: assigned but unused variable - engine
................................................................................................(eval):1: warning: instance variable @engine not initialized
(eval):1: warning: instance variable @_options not initialized
E(eval):1: warning: instance variable @engine not initialized
(eval):1: warning: instance variable @_options not initialized
E(eval):1: warning: instance variable @engine not initialized
F(eval):1: warning: instance variable @engine not initialized
FF(eval):1: warning: instance variable @engine not initialized
.....................................................................................................................................................................................................................
ERROR
 Rabl::Engine #request_format is json by default setup => undefined method `[]' for nil:NilClass occured
 at /Users/dblock/source/rabl/dblock/test/engine_test.rb:32:in `block (4 levels) in <top (required)>'

ERROR
 Rabl::Engine #request_format with a specified format setup => undefined method `[]' for nil:NilClass occured
 at /Users/dblock/source/rabl/dblock/test/engine_test.rb:43:in `block (4 levels) in <top (required)>'

FAILURE
 Rabl::Engine #cache with cache asserts that it => expected :_cache_key to be assigned a value

FAILURE
 Rabl::Engine #cache with cache and options asserts that it => expected :_cache_key to be assigned a value

FAILURE
 Rabl::Engine #cache with cache and options asserts that it => expected :_cache_options to be assigned a value

309 passes, 3 failures, 2 errors in 0.197011 seconds
rake aborted!
```

**Comment by boutil** [comment]
We have the same issue in Debian, with 0.11.6 (the same 3 failures and 2 errors). All tests were passing fine with 0.11.4

**Comment by nesquena** [comment]
Does 0.11.5 pass for you?

**Comment by boutil** [comment]
0.11.5 is also fine.
